apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: ssw-590-final
build:
  artifacts:
  - image: vherzogstevens/ssw-590-final-myapp
    docker:
      dockerfile: Containerfile
deploy:
  helm:
    releases:
    - name: myapp
      chartPath: myapp
      valuesFiles:
      - myapp/values.yaml
      version: 0.1.0
      namespace: default